sylius_resource:
    resources:
        app.article:
            classes:
                model: App\Entity\Article
                form: App\Form\Type\ArticleType
        app.oauth_client:
            classes:
                model: App\Entity\OAuth\Client
