sylius_customer:
    resources:
        customer:
            classes:
                model: AppBundle\Entity\Customer
                form: AppBundle\Form\Type\Customer\CustomerType
        customer_group: ~