sylius_user:
    resources:
        app:
            user:
                classes:
                    model: AppBundle\Entity\AppUser
        admin:
            user:
                classes:
                    model: AppBundle\Entity\AdminUser
                    repository: Sylius\Bundle\UserBundle\Doctrine\ORM\UserRepository
                    form: AppBundle\Form\Type\User\AdminUserType
        admin_oauth:
            user:
                classes:
                    model: Sylius\Component\User\Model\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
                    controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController