# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        sylius_admin_user_provider:
            id: sylius.admin_user_provider.email_or_name_based
    encoders:
        Sylius\Component\User\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        admin:
            context: admin
            pattern: /admin(?:/.*)?$
            form_login:
                provider: sylius_admin_user_provider
                login_path: sylius_backend_login
                check_path: sylius_backend_login_check
                failure_path: sylius_backend_login
                default_target_path: app_backend_dashboard
                use_forward: false
                use_referer: true
            logout:
                path: sylius_backend_logout
                target: sylius_backend_login
            anonymous: true

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/dashboard, role: ROLE_ADMIN }
        - { path: "^/admin.*", role: ROLE_ADMIN }