imports:
    - { resource: services/context.yml }
    - { resource: services/form.yml }
    - { resource: services/installer.yml }
    - { resource: services/listener.yml }
    - { resource: services/menu.yml }
    - { resource: services/validator.yml }
    - { resource: services/view.yml }
