services:
    app.fixture.address:
       class: AppBundle\Fixture\AddressFixture
       arguments:
          - "@app.manager.address"
          - "@app.fixture.example_factory.address"
       tags:
        - { name: sylius_fixtures.fixture }
    app.fixture.admin_user:
       class: AppBundle\Fixture\AdminUserFixture
       arguments:
          - "@sylius.manager.admin_user"
          - "@app.fixture.example_factory.admin_user"
       tags:
        - { name: sylius_fixtures.fixture }
    app.fixture.app_user:
        class: AppBundle\Fixture\AppUserFixture
        arguments:
          - "@sylius.manager.app_user"
          - "@app.fixture.example_factory.app_user"
        tags:
        - { name: sylius_fixtures.fixture }
    app.fixture.customer:
       class: AppBundle\Fixture\CustomerFixture
       arguments:
          - "@sylius.manager.customer"
          - "@app.fixture.example_factory.customer"
       tags:
        - { name: sylius_fixtures.fixture }
    app.fixture.oauth_client:
           class: AppBundle\Fixture\OAuthClientFixture
           arguments:
              - "@app.manager.oauth_client"
              - "@app.fixture.example_factory.oauth_client"
           tags:
            - { name: sylius_fixtures.fixture }