services:
    app.fixture.example_factory.address:
       class: AppBundle\Fixture\Factory\AddressExampleFactory
       arguments:
          - "@app.factory.address"
    app.fixture.example_factory.admin_user:
       class: AppBundle\Fixture\Factory\AdminUserExampleFactory
       arguments:
          - "@sylius.factory.admin_user"
    app.fixture.example_factory.app_user:
       class: AppBundle\Fixture\Factory\AppUserExampleFactory
       arguments:
          - "@sylius.factory.app_user"
          - "@sylius.repository.customer"
    app.fixture.example_factory.customer:
       class: AppBundle\Fixture\Factory\CustomerExampleFactory
       arguments:
          - "@sylius.factory.customer"
    app.fixture.example_factory.oauth_client:
       class: AppBundle\Fixture\Factory\OAuthClientExampleFactory
       arguments:
          - "@app.factory.oauth_client"