# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    pagerfanta.view.foundation:
        class: AppBundle\View\FoundationView

    pagerfanta.view.foundation_translated:
        class: AppBundle\View\FoundationTranslatedView
        arguments:
            - "@pagerfanta.view.foundation"
            - "@translator"
        tags:
            - { name: 'pagerfanta.view', alias: 'foundation_translated' }