app_frontend_address_index:
    methods: [GET]
    path: /adresses/
    defaults:
        _controller: app.controller.address:indexAction
        _sylius:
            template: frontend/address/index.html.twig
            section: frontend
            grid: app_frontend_address
            paginate: 9
