app_backend_dashboard:
    path: /dashboard
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'backend/index.html.twig'

sylius_backend_security:
    resource: "backend/security.yml"